name: Qt Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'  # 指定需要的 Qt 版本
        host: 'linux'      # 使用 Linux 构建环境

    - name: Install Build Tools
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake qt5-qmake qtbase5-dev

    - name: Build Qt Project
      run: |
        mkdir build
        cd build
        qmake ../QtApp/test.pro  # 使用 qmake 生成 Makefile
        make               # 使用 make 构建项目

    - name: Run Tests (Optional)
      run: |
        cd build
        ./test.app  # 替换为生成的可执行文件
