name: Qt Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'linux'

    - name: Install Build Tools
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake qt5-qmake qtbase5-dev

    - name: Build Qt Project
      run: |
        mkdir build
        cd build
        qmake ../QtApp/test.pro
        make

    - uses: actions/upload-artifact@v4
      with:
        name: Monopoly-Qt-Linux
        path: build/monopoly
        if-no-files-found: warn

  build-macos:
    if: ${{ false }}
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'mac'

    - name: Install Build Tools
      run: brew install cmake

    - name: Build Qt Project
      run: |
        mkdir build
        cd build
        qmake ../QtApp/test.pro
        make

    - uses: actions/upload-artifact@v4
      with:
        name: Monopoly-Qt-macOS
        path: build/monopoly.app
        if-no-files-found: warn

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Visual Studio Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8'
        host: 'windows'

    - name: Build Qt Project
      shell: cmd
      run: |
        mkdir build
        cd build
        qmake ..\frontend\frontend.pro
        nmake

    - name: Deploy Qt Dependencies
      shell: cmd
      run: |
        cd build\release
        windeployqt monopoly.exe --release --no-compiler-runtime

    - uses: actions/upload-artifact@v4
      with:
        name: Monopoly-Qt-Windows
        path: build\release\**
        if-no-files-found: warn