name: Qt Build 2

on:
  workflow_dispatch:
  push:

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        host: windows
        version: '6.8.3'
        arch: win64_mingw

    - name: Setup MSYS2 (MSVCRT MinGW)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: inherit
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Build Qt Project
      shell: msys2 {0}
      run: |
        g++ --version
        which g++
        
        mkdir -p build
        cd build
        qmake ../frontend/frontend.pro
        mingw32-make -j$(nproc)

    - name: Deploy Qt Dependencies
      shell: msys2 {0}
      run: |
        cd build/release
        windeployqt monopoly.exe --release --no-compiler-runtime

    - name: Clean up build directory
      shell: msys2 {0}
      run: |
        cd build/release
        rm -f *.o *.a *.h *.cpp

    - uses: actions/upload-artifact@v4
      with:
        name: Monopoly-Qt-Windows
        path: build/release/**
        if-no-files-found: warn
