name: Qt Build 2

on:
  workflow_dispatch:
  push:

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        host: windows
        version: '6.8.3'
        arch: win64_mingw

    - name: Build Qt Project
      shell: cmd
      run: |
        mkdir build
        cd build
        qmake ..\frontend\frontend.pro
        mingw32-make

    - name: Deploy Qt Dependencies
      shell: cmd
      run: |
        cd build\release
        windeployqt monopoly.exe --release --no-compiler-runtime

    - name: Clean up build directory
      shell: cmd
      run: |
        del /s /q build\release\*.o
        del /s /q build\release\*.a
        del /s /q build\release\*.h
        del /s /q build\release\*.cpp

    - uses: actions/upload-artifact@v4
      with:
        name: Monopoly-Qt-Windows
        path: build\release\**
        if-no-files-found: warn
